### PR TITLE
Improved the padding of some icons; added tooltips

### PR DESCRIPTION
**Pull request by JL102**
I added padding to the icons on the bottom to make them feel more comfortable, and added tooltips to those icons too. I also added a left margin to the status icon on the top of the ui. I also changed some of the margins to 6px because I feel like it looks just a liiittle bit nicer.

### CODE REVIEW

**Comment by bpozdena** [comment]
@JL102, thanks for the contribution. 

Next time, please include screenshots from various DEs with their default themes (at least the most common ones KDE, XFCE, Gnome). Very often changing margins can make something look 'nicer' on one DE with specific theme applied, but also make it look uglier in other DEs. 

Seem OK on KDE, so hopefully it will not come back.

**Comment by JL102** [comment]
@bpozdena Do you have any tips on how to switch between different DEs without having to install a whole separate OS? I'm just using Ubuntu Budgie right now.

**Comment by MrGaribaldi** [comment]
Perhaps this guide could be of help?
https://bytexd.com/switch-desktop-environments-ubuntu-debian-commandline/

**Comment by bpozdena** [comment]
I have multiple VMs with different distros, DEs, Wayland, X11. But it's not reasonable for you to have all.. I also would not recommend installing multiple DEs on your work PC as it almost always causes problems and clutter. If you have to do it, do it in a VM that is just for testing.

My priority is good look on KDE with X11 and I can always test that. I can test other DEs as well, it'll just take longer. I barely get 20 free minutes these days😉.

**Pull request merged**
